apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ah5bxaewe-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ah5bxaewe-nodejs 
  name: ah5bxaewe-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ah5bxaewe-nodejs 
